site_name: The Foundry Way
site_description: 'Defence Digital Foundry'
site_author: 'Defence Digital Foundry'

docs_dir: docs/
repo_name: 'defencedigital/the-foundry-way'
repo_url: 'https://github.com/defencedigital/the-foundry-way'
edit_uri: '' #Empty to Disable

theme:
  name: material
  custom_dir: theme/
  language: en
  features:
    - navigation.instant
#    - navigation.tabs
    - navigation.expand
    - navigation.indexes
  favicon: 'assets/img/favicon.ico'

extra_css:
  - assets/styles/extra.css
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js
  - assets/js/extra.js
  - assets/js/cookie-functions.js
  - assets/js/cookie-banner.js
  - assets/js/cookie-page.js
  - assets/js/govuk-frontend-3.14.0.min.js

# Page tree
nav:
  - Home: "index.md"
  - "Comms, content and publishing": "comms-content-and-publishing/index.md"
  - "People, skills and standards":
    - "Communities of practice":
      - "Home": "people-skills-and-standards/communities-of-practice/index.md"
      - "Running a CoP": "people-skills-and-standards/communities-of-practice/running-a-cop.md"
      - "Existing communities":
        - "Product and delivery": "people-skills-and-standards/communities-of-practice/existing-communities/product-and-delivery-cop.md"
        - "User-centred design": "people-skills-and-standards/communities-of-practice/existing-communities/ucd-cop.md"
  - "Product and service delivery":
    - "Naming things": "product-and-service-delivery/naming-things.md"
  - "Data and AI":
    - "Home": "data-ai/index.md"
  - "Software Development":
    - "Home": "software-development/index.md"
#    - "Choosing a programming language":
#    - "Style guides":
    - "How to manage third party software dependencies": "software-development/how-to-manage-third-party-software-dependencies.md"
#    - "Building accessible services":
#    - "Supporting different browsers":
#    - "How to optimise frontend performance":
#    - "Documenting architecture decisions":
#    - "Anticipate security issues using threat modelling":
  - "Technology":
    - "Home": "technology/index.md"
    - "Reliability Engineering": "technology/reliability-engineering/index.md"
    - "Service levels": "technology/reliability-engineering/service-levels.md"
