site_name: Defence Digital Foundry Way
site_description: 'Defence Digital Foundry'
site_author: 'Defence Digital Foundry'

docs_dir: docs/
repo_name: 'defencedigital/the-foundry-way'
repo_url: 'https://github.com/defencedigital/the-foundry-way'
edit_uri: '' #Empty to Disable

theme:
  name: material
  custom_dir: theme/
  language: en
  features:
    - navigation.instant
#    - navigation.tabs
#   - navigation.expand
    - navigation.indexes
  favicon: 'assets/img/favicon.ico'

extra_css:
  - assets/styles/extra.css
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

extra_javascript:
  - assets/js/hljs/highlight.pack.js
  - assets/js/extra.js
  - assets/js/cookie-functions.js
  - assets/js/cookie-banner.js
  - assets/js/cookie-page.js
  - assets/js/govuk-frontend-3.14.0.min.js

# Page tree
nav:

